
```{r}
#| label: fig-barplot
#| cache: true
#| cache.comments: false
#| fig-cap: "GDMT by CRT"

figdata <- rsdata %>%
  select(crt, gdmtdiff_cat, bbldiff, rasiarnidiff, mradiff, loopdiff) %>%
  pivot_longer(cols = c(gdmtdiff_cat, bbldiff, rasiarnidiff, mradiff, loopdiff)) %>%
  mutate(
    name = str_remove_all(name, "diff|_cat"),
    med = factor(name,
      levels = c("gdmt", "bbl", "rasiarni", "mra", "loop"),
      labels = c("Combined", "Beta-blocker", "ACEi/ARB/ARNi", "MRA", "Loop diuretic")
    )
  ) %>%
  group_by(crt, med, .drop = F) %>%
  count(value) %>%
  mutate(
    p = n / sum(n) * 100
  ) %>%
  ungroup()

chifunc <- function(x) {
  tibble(
    pval = fn(chisq.test(rsdata %>% pull(crt), rsdata %>% pull(x))$p.value, p = T, dig = 3),
    med = str_remove_all(x, "diff|_cat")
  )
}

pval <- lapply(c("gdmtdiff_cat", "bbldiff", "rasiarnidiff", "mradiff", "loopdiff"),
  FUN = chifunc
)
pval <- bind_rows(pval) %>%
  mutate(
    med = factor(med,
      levels = c("gdmt", "bbl", "rasiarni", "mra", "loop"),
      labels = c("Combined", "Beta-blocker", "ACEi/ARB/ARNi", "MRA", "Loop diuretic")
    ),
    pval = paste0("P: ", pval),
    value = factor(c(1, 2, 3, 1, 1), levels = 1:3, labels = levels(figdata$value))
  )

p <- ggplot(figdata, aes(x = crt, y = p, fill = value)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = global_cols[4:1]) +
  scale_y_continuous(limits = c(0, 100)) +
  theme_classic() +
  theme(
    text = element_text(size = 20, face = "bold"),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.title = element_blank(),
    axis.text = element_text(color = "black"),
    axis.title.x = element_blank()
  ) +
  labs(y = "Proportion (%)") +
  geom_text(aes(label = fn(p, dec = 0)), position = position_dodge(width = 0.9), vjust = -0.25, size = 6, fontface = "bold") +
  facet_grid(cols = vars(med)) +
  geom_text(
    data = pval,
    mapping = aes(x = 1.5, y = 85, label = pval),
    size = 6, fontface = "bold", hjust = 0.5
  )

create_pptx(p)
p
```

```{r}
#| label: fig-barplot-exarni
#| cache: true
#| cache.comments: false
#| fig-cap: "GDMT by CRT - Excluding ARNi"

figdata <- rsdata %>%
  select(crt, gdmtdiff_cat_exarni, bbldiff, rasiarnidiff_exarni, mradiff, loopdiff) %>%
  pivot_longer(cols = c(gdmtdiff_cat_exarni, bbldiff, rasiarnidiff_exarni, mradiff, loopdiff)) %>%
  mutate(
    name = str_remove_all(name, "diff|_cat|_exarni"),
    med = factor(name,
      levels = c("gdmt", "bbl", "rasiarni", "mra", "loop"),
      labels = c("Combined", "Beta-blocker", "ACEi/ARB/ARNi", "MRA", "Loop diuretic")
    )
  ) %>%
  filter(!is.na(value)) %>%
  group_by(crt, med, .drop = F) %>%
  count(value) %>%
  mutate(
    p = n / sum(n) * 100
  ) %>%
  ungroup()

chifunc <- function(x) {
  tibble(
    pval = fn(chisq.test(rsdata %>% pull(crt), rsdata %>% pull(x))$p.value, p = T, dig = 3),
    med = str_remove_all(x, "diff|_cat|_exarni")
  )
}

pval <- lapply(c("gdmtdiff_cat_exarni", "bbldiff", "rasiarnidiff_exarni", "mradiff", "loopdiff"),
  FUN = chifunc
)
pval <- bind_rows(pval) %>%
  mutate(
    med = factor(med,
      levels = c("gdmt", "bbl", "rasiarni", "mra", "loop"),
      labels = c("Combined", "Beta-blocker", "ACEi/ARB/ARNi", "MRA", "Loop diuretic")
    ),
    pval = paste0("P: ", pval),
    value = factor(c(1, 2, 3, 1, 1), levels = 1:3, labels = levels(figdata$value))
  )

p <- ggplot(figdata, aes(x = crt, y = p, fill = value)) +
  geom_bar(stat = "identity", position = "dodge") +
  scale_fill_manual(values = global_cols[4:1]) +
  scale_y_continuous(limits = c(0, 100)) +
  theme_classic() +
  theme(
    text = element_text(size = 20, face = "bold"),
    legend.position = "bottom",
    legend.box = "vertical",
    legend.title = element_blank(),
    axis.text = element_text(color = "black"),
    axis.title.x = element_blank()
  ) +
  labs(y = "Proportion (%)") +
  geom_text(aes(label = fn(p, dec = 0)), position = position_dodge(width = 0.9), vjust = -0.25, size = 6, fontface = "bold") +
  facet_grid(cols = vars(med)) +
  geom_text(
    data = pval,
    mapping = aes(x = 1.5, y = 85, label = pval),
    size = 6, fontface = "bold", hjust = 0.5
  )

create_pptx(p)
p
```
