```{r}
#| label: fufunc
#| cache: true
#| cache.comments: false

fufunc_inner <- function(data, medvar) {
  out1 <- data %>%
    filter(!is.na(shf_bpsys_diff) & !is.na(!!sym(medvar))) %>%
    group_by(crt, !!sym(medvar), .drop = F) %>%
    reframe(
      med = quantile(shf_bpsys_diff, na.rm = T, probs = c(0.5)),
      q1 = quantile(shf_bpsys_diff, na.rm = T, probs = c(0.25)),
      q3 = quantile(shf_bpsys_diff, na.rm = T, probs = c(0.75)),
      n = n()
    ) %>%
    mutate(
      out = paste0(n, ", ", fn(med, 1), " [", fn(q1, 1), "-", fn(q3, 1), "]"),
      out = case_when(
        n < 10 ~ "<10",
        TRUE ~ out
      )
    ) %>%
    ungroup() %>%
    select(crt, !!sym(medvar), out) %>%
    pivot_wider(names_from = c(crt, !!sym(medvar)), values_from = c(out)) %>%
    mutate(
      Med = medvar,
      lab = "Systolic blood pressure (mmHg)"
    )

  out2 <- data %>%
    filter(!is.na(shf_gfrckdepi_diff) & !is.na(!!sym(medvar))) %>%
    group_by(crt, !!sym(medvar), .drop = F) %>%
    reframe(
      med = quantile(shf_gfrckdepi_diff, na.rm = T, probs = c(0.5)),
      q1 = quantile(shf_gfrckdepi_diff, na.rm = T, probs = c(0.25)),
      q3 = quantile(shf_gfrckdepi_diff, na.rm = T, probs = c(0.75)),
      n = n()
    ) %>%
    mutate(
      out = paste0(n, ", ", fn(med, 1), " [", fn(q1, 1), "-", fn(q3, 1), "]"),
      out = case_when(
        n < 10 ~ "<10",
        TRUE ~ out
      )
    ) %>%
    ungroup() %>%
    select(crt, !!sym(medvar), out) %>%
    pivot_wider(names_from = c(crt, !!sym(medvar)), values_from = c(out)) %>%
    mutate(
      Med = medvar,
      lab = "eGFR (mL/min/1.73 m²)"
    )

  out <- bind_rows(out1, out2)
  return(out)
}

fufunc <- function(data) {
  rasiarni <- fufunc_inner(data, medvar = "rasiarnidiff_cat2")
  rasiarni_exarni <- fufunc_inner(data, medvar = "rasiarnidiff_exarni_cat2")
  mra <- fufunc_inner(data, medvar = "mradiff_cat2")
  bbl <- fufunc_inner(data, medvar = "bbldiff_cat2")
  loop <- fufunc_inner(data, medvar = "loopdiff_inccat2")

  colnames(loop) <- str_replace_all(colnames(loop), "Decrease", "XXXX")
  colnames(loop) <- str_replace_all(colnames(loop), "Increase", "Decrease")
  colnames(loop) <- str_replace_all(colnames(loop), "XXXX", "Increase")

  tabgdmt <- bind_rows(bbl, rasiarni, rasiarni_exarni, mra, loop)

  tabgdmt <- tabgdmt %>%
    mutate(
      Med = str_remove_all(Med, "diff_cat2|diff_inccat2|diff|_cat2"),
      Med = factor(Med,
        levels = c("bbl", "rasiarni", "rasiarni_exarni", "mra", "loop"),
        labels = c("Beta-blocker", "ACEi/ARB/ARNi", "ACEi/ARB", "MRA", "Loop diuretic")
      )
    ) %>%
    select(Med, lab, everything()) %>%
    mutate(Med = if_else(lab == "Systolic blood pressure (mmHg)", Med, NA))

  cn <- c("Medication", "", rep(c("Decrease (Increase*)/ Stable", "Increase (Decrease*)"), 2))

  # excel
  make_one_xlsxsheet(tabgdmt, colnames = cn)

  cn <- sanitize_text(cn)

  default_kable(tabgdmt,
    escape = FALSE,
    col.names = cn
  ) %>%
    add_header_above(c(" " = 1, " " = 1, "No CRT" = 2, "CRT" = 2)) %>%
    footnote(
      footnote_order = c("general", "symbol", "alphabet"),
      general_title = "",
      general = c(
        "Presented as N, median [q1-q3] value at 1.5 year follow-up - value at baseline."
      ),
      symbol = c(
        "Loop diuretic"
      )
    ) %>%
    column_spec(c(3:6), width = "4cm")
}
```

```{r}
#| label: tbl-fu
#| cache: true
#| cache.comments: false
#| dependson: fufunc
#| tbl-cap: "Difference between 1.5 year follow-up and baseline by CRT and increase in GDMT and decrease in loop diuretic"
#| tbl-pos: "H"

fufunc(data = rsdata_fu)
```

```{r}
#| label: tbl-fu-pp
#| cache: true
#| cache.comments: false
#| dependson: fufunc
#| tbl-cap: "Difference between 1.5 year follow-up and baseline by CRT and increase in GDMT and decrease in loop diuretic - Per-protocol"
#| tbl-pos: "H"

fufunc(data = rsdata_fu %>% filter(senscrtfu))
```
