```{r}
#| label: logregmedfunc2
#| cache: true
#| cache.comments: false

medfunc_inner2 <- function(data, impdata, novars, medvar, nomeddiff, val = "Decrease") {
  modvarstmp <- c(modvars, "sos_lm_rasiarni1", "sos_lm_bbl1", "sos_lm_mra1", "sos_lm_loop1")
  modvarstmp <- setdiff(modvarstmp, novars)
  modvarsmedtmp <- c(modvars, "sos_lm_rasiarni1", "sos_lm_bbl1", "sos_lm_mra1", "sos_lm_loop1", "bbldiff_inccat2", "rasiarnidiff_inccat2", "mradiff_inccat2", "loopdiff_inccat2")
  modvarsmedtmp <- setdiff(modvarsmedtmp, nomeddiff)
  modvarsmedtmp <- setdiff(modvarsmedtmp, novars)

  moduni <- summary(glm(formula(paste0(medvar, " == '", val, "' ~ crt")),
    family = binomial(link = "logit"), data = data
  ))

  modadj <- with(impdata, glm(formula(paste0(medvar, " == '", val, "' ~ crt + ", paste(modvarstmp, collapse = " + "))),
    family = binomial(link = "logit")
  ))
  modadj <- summary(pool(modadj))

  modadjmed <- with(impdata, glm(formula(paste0(medvar, " == '", val, "' ~ crt + ", paste(modvarsmedtmp, collapse = " + "))),
    family = binomial(link = "logit")
  ))
  modadjmed <- summary(pool(modadjmed))

  ds <- rsdata %>%
    group_by(crt) %>%
    count(!!sym(medvar)) %>%
    mutate(
      p = fn(n / sum(n) * 100, 1),
      out = paste0(n, " (", p, ")")
    ) %>%
    ungroup() %>%
    filter(!!sym(medvar) == val)

  out <- tibble(
    Med = medvar,
    ds_nocrt = ds %>% filter(crt == "No CRT") %>% pull(out),
    ds_crt = ds %>% filter(crt == "CRT") %>% pull(out),
    uni = paste0(
      fn(exp(moduni$coefficients[2, "Estimate"]), 2), " (",
      fn(exp(moduni$coefficients[2, "Estimate"] - global_z05 * moduni$coefficients[2, "Std. Error"]), 2), "-",
      fn(exp(moduni$coefficients[2, "Estimate"] + global_z05 * moduni$coefficients[2, "Std. Error"]), 2), "), ",
      fn(moduni$coefficients[2, "Pr(>|z|)"], dig = 3, p = T)
    ),
    mult = paste0(
      fn(exp(modadj$estimate[2]), 2), " (",
      fn(exp(modadj$estimate[2] - global_z05 * modadj$std.error[2]), 2), "-",
      fn(exp(modadj$estimate[2] + global_z05 * modadj$std.error[2]), 2), "), ",
      fn(modadj$p.value[2], dig = 3, p = T)
    ),
    multmed = paste0(
      fn(exp(modadjmed$estimate[2]), 2), " (",
      fn(exp(modadjmed$estimate[2] - global_z05 * modadjmed$std.error[2]), 2), "-",
      fn(exp(modadjmed$estimate[2] + global_z05 * modadjmed$std.error[2]), 2), "), ",
      fn(modadjmed$p.value[2], dig = 3, p = T)
    )
  )
  return(out)
}

medfunc2 <- function(data, impdata, novars = NULL) {
  rasiarni <- medfunc_inner2(data, impdata, novars, medvar = "rasiarnidiff_inccat2", nomeddiff = c("rasiarnidiff_inccat2"))
  rasiarni_exarni <- medfunc_inner2(data, impdata, novars, medvar = "rasiarnidiff_exarni_inccat2", nomeddiff = c("rasiarnidiff_inccat2"))
  mra <- medfunc_inner2(data, impdata, novars, medvar = "mradiff_inccat2", nomeddiff = c("mradiff_inccat2"))
  bbl <- medfunc_inner2(data, impdata, novars, medvar = "bbldiff_inccat2", nomeddiff = c("bbldiff_inccat2"))
  tabgdmt <- bind_rows(bbl, rasiarni, rasiarni_exarni, mra)

  tabgdmt <- tabgdmt %>%
    mutate(
      Med = str_remove_all(Med, "_|inc|cat2|diff"),
      Med = factor(Med,
        levels = c("bbl", "rasiarni", "rasiarniexarni", "mra", "loop"),
        labels = c("Beta-blocker", "ACEi/ARB/ARNi", "ACEi/ARB", "MRA", "Loop diuretic")
      )
    )

  cn <- c("Medication", "No CRT", "CRT", "Crude", "Adjusted baseline", "Adjusted baseline + change in medications")

  # excel
  make_one_xlsxsheet(tabgdmt, colnames = cn)

  cn <- sanitize_text(cn)

  default_kable(tabgdmt,
    escape = FALSE,
    col.names = cn
  ) %>%
    add_header_above(c(" " = 1, "n (%) Decrease" = 2, "Odds Ratio (95% CI), p-value" = 3))
}
```

```{r}
#| label: tbl-logregmed2
#| cache: true
#| cache.comments: false
#| dependson: logregmedfunc2
#| tbl-cap: "Association between CRT and decrease in GDMT"
#| tbl-pos: "H"

medfunc2(data = rsdata, impdata = imprsdata)
```

```{r}
#| label: tbl-logregmed-hypobp2
#| cache: true
#| cache.comments: false
#| dependson: logregmedfunc2
#| tbl-cap: "Association between CRT and decrease in GDMT - systolic blood pressure < 110 (mmHg)"
#| tbl-pos: "H"

medfunc2(data = rsdata %>% filter(shf_bpsys_cat == "<110" & !is.na(shf_bpsys_cat)), impdata = imprsdatahypo, novars = "shf_bpsys_cat")
```

```{r}
#| label: tbl-logregmed-durhf12
#| cache: true
#| cache.comments: false
#| dependson: logregmedfunc2
#| tbl-cap: "Association between CRT and decrease in GDMT - duration of HF 3-9 (months)"
#| tbl-pos: "H"

medfunc2(data = rsdata %>% filter(sos_durationhf_cat == "3-9"), impdata = imprsdatadurhf1, novars = c("sos_durationhf_cat"))
```

```{r}
#| label: tbl-logregmed-durhf22
#| cache: true
#| cache.comments: false
#| dependson: logregmedfunc2
#| tbl-cap: "Association between CRT and decrease - duration of HF 10-18 (months)"
#| tbl-pos: "H"

medfunc2(data = rsdata %>% filter(sos_durationhf_cat == "10-18"), impdata = imprsdatadurhf2, novars = c("sos_durationhf_cat"))
```

```{r}
#| label: tbl-logregmed-durhf32
#| cache: true
#| cache.comments: false
#| dependson: logregmedfunc2
#| tbl-cap: "Association between CRT and decrease - duration of HF >= 19 (months)"
#| tbl-pos: "H"

medfunc2(data = rsdata %>% filter(sos_durationhf_cat == ">=19"), impdata = imprsdatadurhf3, novars = c("sos_durationhf_cat"))
```
